apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: zentao
  name: zentao
spec:
  clusterIP: None
  ports:
    - name: "http"
      port: 80
      targetPort: 80
  selector:
    app: zentao
  type: ClusterIP