apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zentao-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.zentao.persistence.capacity }}
      storageClass: {{ .Values.zentao.persistence.storageClass }}
